---
- name: Remove packages on CentOS or RedHat
  yum:
    name: "{{ item }}"
    state: absent
  loop: "{{ package_list }}"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
  become: yes
  become_user: root

- name: Remove packages on Debian or Ubuntu
  apt:
    name: "{{ item }}"
    state: absent
  loop: "{{ package_list }}"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  become: yes
  become_user: root

