---
- name: Insert block of text at the end of /etc/rsyslog.conf
  blockinfile:
    path: /etc/rsyslog.conf
    block: |
      $FileCreateMode 0640

- name: Set ownership and permissions on /etc/rsyslog.d directory
  file:
    path: /etc/rsyslog.d
    owner: root
    group: root
    mode: '0640'
    recurse: yes

- name: Set permissions on /var/log directory
  file:
    path: /var/log
    owner: root
    group: root
    mode: '0775'
    recurse: no
    state: directory

