---
- name: Gather facts for ansible-w-vm1
  hosts: linux-host1
  gather_facts: yes

  tasks:
    - name: Display gathered facts
      debug:
        var: ansible_facts

    - name: Display specific facts
      debug:
        msg: "FQDN: {{ ansible_facts['fqdn'] }}, IPv4 Address: {{ ansible_facts['default_ipv4']['address'] }}, Short Hostname: {{ ansible_facts['hostname'] }}"

